export const GalleryData = [
    {
        id:1,
        titile:"car",
        image:"./images/img-1.jpg"
    },
    {
        id:2,
        titile:"car",
        image:"./images/img-2.jpg"
    },
    {
        id:3,
        titile:"car",
        image:"./images/img-3.jpg"
    },
    {
        id:4,
        titile:"car",
        image:"./images/img-4.jpg"
    },
    {
        id:5,
        titile:"car",
        image:"./images/img-5.jpeg"
    },
    {
        id:6,
        titile:"car",
        image:"./images/img-6.jpg"
    },
    {
        id:7,
        titile:"bike",
        image:"./images/img-7.jpg"
    },
    {
        id:8,
        titile:"bike",
        image:"./images/img-8.jpg"
    },
    {
        id:9,
        titile:"bike",
        image:"./images/img-9.jpg"
    },
    {
        id:10,
        titile:"bike",
        image:"./images/img-10.jpg"
    },
    {
        id:11,
        titile:"cycle",
        image:"./images/img-11.jpg"
    },
    {
        id:12,
        titile:"cycle",
        image:"./images/img-12.jpg"
    },
    {
        id:13,
        titile:"cycle",
        image:"./images/img-13.jpg"
    },
]